channels:
- conda-forge
dependencies:
- python=3.8.19
- pip<=20.3.3
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.19.5
  - packaging==24.0
  - pandas==1.2.3
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==0.24.1
  - scipy==1.9.1
name: mlflow-env
